name: flutter_web_auth_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bootstrap_icons: ^1.11.1
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  font_awesome_flutter: ^10.6.0
  github_sign_in: ^0.0.5-dev.4
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  toastification: ^1.1.0
  twitter_login: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
