name: flutter_web_auth_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  appwrite: ^11.0.1
  bootstrap_icons: ^1.11.1
  elevarm_ui: ^0.9.4
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.12
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  flutter_login_facebook: ^1.9.0
  font_awesome_flutter: ^10.6.0
  github_sign_in_plus: ^0.0.2
  google_sign_in: ^6.1.6
  googleapis: ^3.0.0
  shared_preferences: ^2.2.2
  shimmer_animation: ^2.0.0
  toastification: ^1.1.0
  twitter_login: ^4.4.0
  ui_package:
   git:
    url: https://github.com/x-brymo/ui_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
  -asset/image/