// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5dRCloy3HS8JFjXSJ29G-7jYEKrJUpQ',
    appId: '1:408175319305:web:45b1e3c271d0fe7a1ddbd8',
    messagingSenderId: '408175319305',
    projectId: 'flutter-web-auth-app',
    authDomain: 'flutter-web-auth-app.firebaseapp.com',
    storageBucket: 'flutter-web-auth-app.appspot.com',
    measurementId: 'G-R9M82YMW76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMc_Ns1IkvWsn50pc8GmOGbEx9FT61n2A',
    appId: '1:408175319305:android:0aa8aa60a798c1311ddbd8',
    messagingSenderId: '408175319305',
    projectId: 'flutter-web-auth-app',
    storageBucket: 'flutter-web-auth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBElfzUtWxebH09aQ_z3dncPNd4yqCDkhY',
    appId: '1:408175319305:ios:6d200a70d893a3941ddbd8',
    messagingSenderId: '408175319305',
    projectId: 'flutter-web-auth-app',
    storageBucket: 'flutter-web-auth-app.appspot.com',
    iosBundleId: 'com.example.flutterWebAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBElfzUtWxebH09aQ_z3dncPNd4yqCDkhY',
    appId: '1:408175319305:ios:fe3be48e5be609291ddbd8',
    messagingSenderId: '408175319305',
    projectId: 'flutter-web-auth-app',
    storageBucket: 'flutter-web-auth-app.appspot.com',
    iosBundleId: 'com.example.flutterWebAuthApp.RunnerTests',
  );
}
